***Variables***
${pay_button_locator}          //button/span[text()='PAY']
${pay_method_locator}          //label//input[@value='creditCard']
${next_button_locator}         //button/span[text()='Next']
${card_number_locator}         //input[@id='basic_bin']
${exp_date_locator}            //input[@id='basic_exp'] 
${cvc_code_locator}            //input[@id='basic_cvc']
${card_owner_locator}          //input[@id='basic_owner']
${confirm_button_locator}      //button/span[text()='Confirm Payment']
${popup_payment__locator}      //div[@class='ant-modal-content']
${popup_text_locator}          //div[@class='ant-modal-confirm-content']
${popup_button__locator}       //button/span[text()='OK']
${payment_details__locator}    //div[@class='success-description']
${payment_button_locator}      //button[@class='css-eq3tly ant-btn ant-btn-link']